import Head from 'next/head'

export default function Layout({title, children}) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-full flex flex-col items-center justify-start p-4'>
        {children}
      </main>
    </>
  )
}
